name: Difficulty Calculation
on:
  issue_comment:
    types: [ created ]

jobs:
  diffcalc:
    name: Run
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '!diffcalc') && (github.event.comment.author_association == 'MEMBER' || github.event.comment.author_association == 'OWNER')
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout diffcalc-sheet-generator
        uses: actions/checkout@v3
        with:
          path: 'diffcalc-sheet-generator'
          repository: 'smoogipoo/diffcalc-sheet-generator'

      - name: Setup
        run: |
          generator_dir="${{ github.workspace }}/diffcalc-sheet-generator"
          generator_env="$generator_dir/.env"
          google_creds_file="$generator_dir/google-credentials.json"

          # Add default environment
          cat "${{ github.workspace }}/.env" | sed -nr "s/^([^=]+)=(.*)$/\1=\2/p" | while read -r line; do
              opt=$(echo $line | sed -nr "s/^([^=]+)=(.*)$/\1/p")
              sed -i "s/^${opt}.*$/$line/" "$generator_env"
          done

          # Add comment environment
          echo "${{ github.event.comment.body }}" | sed -nr "s/^([^=]+)=(.*)$/\1=\2/p" | while read -r line; do
              opt=$(echo $line | sed -nr "s/^([^=]+)=(.*)$/\1/p")
              sed -i "s/^${opt}.*$/$line/" "$generator_env"
          done

          # Add GH token
          sed -i "s/^GH_TOKEN=.*$/GH_TOKEN=${{ secrets.DIFFCALC_GITHUB_TOKEN }}/" "$generator_env"

          # Add Google credentials
          echo "{{ secrets.DIFFCALC_GOOGLE_CREDENTIALS }}" > "$google_creds_file"
          sed -i "s,^GOOGLE_CREDENTIALS_FILE=.*$,GOOGLE_CREDENTIALS_FILE=$google_creds_file," "$generator_env"